# Generated by Django 4.2.1 on 2023-05-06 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("creation_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Amazona", "Amazona"),
                            ("Antioquia", "Antioquia"),
                            ("Arauca", "Arauca"),
                            ("Atlántico", "Atlántico"),
                            ("Bolívar", "Bolívar"),
                            ("Boyacá", "Boyacá"),
                            ("Caldas", "Caldas"),
                            ("Caquetá", "Caquetá"),
                            ("Casanare", "Casanare"),
                            ("Cauca", "Cauca"),
                            ("Cesar", "Cesar"),
                            ("Chocó", "Chocó"),
                            ("Córdoba", "Córdoba"),
                            ("Cundinamarca", "Cundinamarca"),
                            ("Guainía", "Guainía"),
                            ("Guaviare", "Guaviare"),
                            ("Huila", "Huila"),
                            ("La_Guajira", "La_Guajira"),
                            ("Magdalena", "Magdalena"),
                            ("Meta", "Meta"),
                            ("Nariño", "Nariño"),
                            ("Norte_de_Santander", "Norte_de_Santander"),
                            ("Putumayo", "Putumayo"),
                            ("Quindío", "Quindío"),
                            ("Risaralda", "Risaralda"),
                            ("San_Andrés", "San_Andrés"),
                            ("Santander", "Santander"),
                            ("Sucre", "Sucre"),
                            ("Tolima", "Tolima"),
                            ("Valle_del_Cauca", "Valle_del_Cauca"),
                            ("Vichada", "Vichada"),
                            ("Vaupés", "Vaupés"),
                        ],
                        max_length=100,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="agencyfront.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeasingPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actualzation_date",
                    models.DateField(auto_created=True, auto_now_add=True),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("COP", "Peso Colombiano"), ("USD", "USA Dollar")],
                        max_length=5,
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agencyfront.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="static/images/%Y/%m/%d/")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agencyfront.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommercialRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "leasing_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agencyfront.leasingprice",
                    ),
                ),
                (
                    "lessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agencyfront.user",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agencyfront.property",
                    ),
                ),
            ],
        ),
    ]
